# Generated by Django 5.0.1 on 2024-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subplanfeature',
            name='subplan',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
