# Generated by Django 4.2.7 on 2024-02-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
